"""initial schema

Revision ID: 7ffb31fc807f
Revises: 
Create Date: 2026-04-01 23:36:46.374272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffb31fc807f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_releases_imdb', 'releases', ['imdb_id'], unique=False, postgresql_where='imdb_id IS NOT NULL')
    op.create_index('idx_releases_tmdb', 'releases', ['tmdb_id'], unique=False, postgresql_where='tmdb_id IS NOT NULL')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('verification_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('disc_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('edition_name', sa.String(length=200), nullable=True),
    sa.Column('total_discs', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disc_sets_release', 'disc_sets', ['release_id'], unique=False)
    op.create_table('user_oauth_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_oauth_provider_id')
    )
    op.create_index('idx_user_oauth_links_user', 'user_oauth_links', ['user_id'], unique=False)
    op.create_table('discs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('upc', sa.String(length=20), nullable=True),
    sa.Column('disc_label', sa.String(length=100), nullable=True),
    sa.Column('disc_number', sa.SmallInteger(), nullable=False),
    sa.Column('total_discs', sa.SmallInteger(), nullable=False),
    sa.Column('edition_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('disc_set_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disc_set_id'], ['disc_sets.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index('idx_discs_fingerprint', 'discs', ['fingerprint'], unique=False)
    op.create_index('idx_discs_label', 'discs', ['disc_label'], unique=False, postgresql_where='disc_label IS NOT NULL')
    op.create_index('idx_discs_status', 'discs', ['status'], unique=False)
    op.create_index('idx_discs_upc', 'discs', ['upc'], unique=False, postgresql_where='upc IS NOT NULL')
    op.create_table('disc_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disc_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('edit_type', sa.String(length=30), nullable=True),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('edit_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disc_releases',
    sa.Column('disc_id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('disc_id', 'release_id')
    )
    op.create_table('disc_titles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disc_id', sa.UUID(), nullable=False),
    sa.Column('title_index', sa.SmallInteger(), nullable=False),
    sa.Column('title_type', sa.String(length=30), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('chapter_count', sa.SmallInteger(), nullable=True),
    sa.Column('is_main_feature', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disc_id', 'title_index', name='uq_disc_titles_index')
    )
    op.create_index('idx_disc_titles_disc', 'disc_titles', ['disc_id'], unique=False)
    op.create_table('disc_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disc_title_id', sa.UUID(), nullable=False),
    sa.Column('track_type', sa.String(length=10), nullable=False),
    sa.Column('track_index', sa.SmallInteger(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('codec', sa.String(length=30), nullable=True),
    sa.Column('channels', sa.SmallInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['disc_title_id'], ['disc_titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disc_tracks_title', 'disc_tracks', ['disc_title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_disc_tracks_title', table_name='disc_tracks')
    op.drop_table('disc_tracks')
    op.drop_index('idx_disc_titles_disc', table_name='disc_titles')
    op.drop_table('disc_titles')
    op.drop_table('disc_releases')
    op.drop_table('disc_edits')
    op.drop_index('idx_discs_upc', table_name='discs', postgresql_where='upc IS NOT NULL')
    op.drop_index('idx_discs_status', table_name='discs')
    op.drop_index('idx_discs_label', table_name='discs', postgresql_where='disc_label IS NOT NULL')
    op.drop_index('idx_discs_fingerprint', table_name='discs')
    op.drop_table('discs')
    op.drop_index('idx_user_oauth_links_user', table_name='user_oauth_links')
    op.drop_table('user_oauth_links')
    op.drop_index('idx_disc_sets_release', table_name='disc_sets')
    op.drop_table('disc_sets')
    op.drop_table('users')
    op.drop_index('idx_releases_tmdb', table_name='releases', postgresql_where='tmdb_id IS NOT NULL')
    op.drop_index('idx_releases_imdb', table_name='releases', postgresql_where='imdb_id IS NOT NULL')
    op.drop_table('releases')
    # ### end Alembic commands ###
