"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/lib/auth";
import SubmitForm from "@/components/SubmitForm";

export default function SubmitPage() {
  const { user, loading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && !user) {
      router.push("/?message=login_required");
    }
  }, [loading, user, router]);

  if (loading) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-12 text-center text-neutral-400 text-sm">
        Loading…
      </div>
    );
  }

  if (!user) {
    return null; // Will redirect via useEffect
  }

  return (
    <div className="mx-auto max-w-2xl px-4 py-8">
      <h1 className="text-2xl font-bold tracking-tight mb-2">Submit a Disc</h1>
      <p className="text-sm text-neutral-500 mb-6">
        Upload a fingerprint JSON file generated by the OVID CLI, then fill in
        release details.
      </p>
      <SubmitForm />
    </div>
  );
}
